name: pokebag
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.1
  lazy_load_scrollview: ^1.3.0
  lottie: ^1.2.2
  responsive_sizer: ^3.0.5+1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/animations/
    - assets/icons/
  uses-material-design: true
